_target_: src.models.dogbreed_classifier.DogBreedGenericClassifier

model_name: "resnet50"
num_classes: 10
pretrained: true

optimizer:
  # _target_: torch.optim.Adam
  # _partial_: true
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  # _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  # _partial_: true
  mode: min
  factor: 0.1
  patience: 10
  min_lr: 1e-6
  verbose: True
